apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: tripviewer