# Taken from 
# https://learn.microsoft.com/en-us/azure/aks/azure-ad-rbac?tabs=portal#create-aks-cluster-resources-for-app-devs

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-user-full-access
subjects:
- kind: Group
  namespace: web
  name: groupObjectId

#TODO: from website: replace groupObjectId with the group object ID output from the previous command.