apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: api
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: user-java