apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api
spec:
  ports:
    - targetPort: 80
      name: poi
      port: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: poi
