apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofiles
  namespace: api
  labels:
    app: userprofiles
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofiles
  template:
    metadata:
      labels:
        app: userprofiles
    spec:
      containers:
      - name: userprofiles
        image: registryekd7054.azurecr.io/tripinsights/userprofile:1.0
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true
        ports:
        - containerPort: 80
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
        
